djangoAuthProject/djangoAuthProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
]

djangoAuthProject/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('create-post/', views.create_post, name='create-post'),
    path('delete-post/', views.delete_post, name='delete-post'),
    path('ban-user/', views.ban_user, name='ban-user'),
]

djangoAuthProject/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

djangoAuthProject/main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

from .models import Post

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body']

djangoAuthProject/main/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group, User

from .forms import PostForm, RegistrationForm
from .models import Post

class HomeView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'main/home.html'
    login_url = '/login/'

def sign_up(request):

    if request.method =='POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse(viewname='main:home'))
    
    else:
        form = RegistrationForm()

    return render(request, 'registration/sign-up.html', { "form" : form })

@permission_required('main.add_post', raise_exception=True)
@login_required
def create_post(request):

    if request.method == "POST":

        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect(reverse(viewname='main:home'))
        
    else:
        form = PostForm()
    
    return render(request, 'main/create-post.html', { "form" : form })
   

@login_required
def delete_post(request):
    post_id = request.POST.get("post_id")
    post = Post.objects.filter(id=post_id).first()

    if post and (post.user == request.user or request.user.has_perm('main.delete_post')):
        post.delete()
    
    return redirect(reverse('main:home'))

def ban_user(request):

    user_id = request.POST.get("user_id")
    user = User.objects.filter(id=user_id).first()

    print(f"user ban: {user}")
    if user and request.user.is_superuser:


        try:
            default_group = Group.objects.filter(name='default').first()
            default_group.user_set.remove(user)
        except:
            pass
        
        try:
            mod_group = Group.objects.filter(name='mod').first()
            mod_group.user_set.remove(user)
        except:
            pass

    return redirect(reverse('main:home'))

djangoAuthProject/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>{% block title %} my app {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-black">
      <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-light" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="/create-post">Post</a>
          </li>
        </ul>

        <div class="navbar-nav row align-items-center me-3">
          {% if user.is_authenticated %}
          <div class="text-light text-nowrap col">
            Logged in as: <span class="p-2 text-black text-center bg-light-subtle rounded">{{user.username}}</span>
          </div>
          <div class="nav-item col">
            <form action="/logout/" method="post">
              {% csrf_token %}
              <button class="btn btn-primary" type="submit">Logout</button>
            </form>
          </div>
          {% else %}
          <a class="nav-link btn bg-dark-subtle" aria-current="page" href="/login">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mt-5">{% block content %} {% endblock %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

djangoAuthProject/main/templates/main/create-post.html
{% extends 'main/base.html' %} 
{% block title %} Create post {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Create a post</h1>

<form method="post">
    {% csrf_token %} {{ form|crispy }}

  <button type="submit" class="btn btn-primary">Post</button>

</form>

{% endblock %}

djangoAuthProject/main/templates/main/home.html
{% extends "main/base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
<div>
    {% for post in post_list %}
        <div class="card mb-4">
            <div class="card-header">
                @{{ post.user.username }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text">{{post.body}}</p>
                <div class="d-flex gap-3">
                    {% if user == post.user or perms.main.delete_post %}
                    <form class="" action="{% url 'main:delete-post' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" name="post_id" value={{post.id}}>Delete post</button>
                    </form>
                    {% endif %}

                    {% if user.is_superuser %}
                    
                        {% if post.user.groups.exists %}
                            <form action="{% url 'main:ban-user' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning" name="user_id" value={{post.user.id}}>Ban user</button>
                            </form>
                        {% else %}
                            <form action="{% url 'main:ban-user' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success" name="user_id" value={{post.user.id}}>Grant permission</button>
                            </form>
                        {% endif %}
                        
                    {% endif %}
                </div>
            </div>
            <div class="card-footer text-muted">
                {{post.created_at}}
            </div>
        </div>
        {% empty %}
            <p class="text-center">No posts found!</p>
    {% endfor %}
</div>

{% endblock %}